Rename contentTypes to collectionTypes
strapi/gatsby-source-strapi pull request #198
Opened 2021-04-30 14:16 UTC by remidej

2021-05-07 12:12 UTC, alexandrebodin requested changes

2021-05-07 12:12 UTC, alexandrebodin commented on README.md
>            name: `collection-name`,
can you add an example with endpoint & api options too

2021-05-07 12:12 UTC, alexandrebodin commented on src/index.js
> +  if (options.contentTypes) {
Let's not keep some deprecation warning in the code since we are releasing a new major version. We will add this to the release changelog instead

2021-05-11 10:26 UTC, remidej commented
I started doing quite a few readme changes, so I ended up removing them from this PR, since they were a bit out of scope. I'll create another PR for the readme just after this

2021-05-11 14:59 UTC, alexandrebodin approved these changes
LGTM

2021-05-11 14:59 UTC, merged