Allow fetching all items with multiple calls instead of a very large one
strapi/gatsby-source-strapi pull request #199
Opened 2021-04-30 16:16 UTC by philippeauriach

Especially usefull on servers limiting the duration of requests (for example Heroku, which limits to 30sec each request).

Passing the loop parameter will perform multiple calls until all items are downloaded.

Readme.md updated with an example.

2021-04-30 16:16 UTC, strapi-cla commented
[![CLA assistant check](https://cla.strapi.io/pull/badge/not_signed)](https://cla.strapi.io/strapi/gatsby-source-strapi?pullRequest=199) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.strapi.io/strapi/gatsby-source-strapi?pullRequest=199) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.strapi.io/check/strapi/gatsby-source-strapi?pullRequest=199) it.</sub>

2021-07-08 18:53 UTC, tonoli submitted a review, later dismissed

2021-07-11 15:06 UTC, philippeauriach commented
Hi @tonoli, thanks for reviewing. Could you tell what's missing in this issue before it could be merged ?

2021-07-27 09:28 UTC, remidej requested changes
Thanks for taking the time to work on this! It can be a pretty good feature for a future release. I've added my review, don't hesitate to comment if you have questions

2021-07-27 09:28 UTC, remidej commented on README.md
> +          loop: 100,
The loop is an implementation detail of how we connect to the API. So I'd recommend moving the loop option inside of the `api` object

2021-07-27 09:28 UTC, remidej commented on README.md
> +If you have many items in a collection and a single API call is a bit heavy for your server, you can split it into multiple requests.
```suggestion
When you have many items in a collection, a single API call can be a bit heavy for your server. In that case, you can split your data fetching into multiple requests.
```

2021-07-27 09:28 UTC, remidej commented on src/fetch.js
> +  const { endpoint, api, loop } = entityDefinition;
Same as above, I recommended getting the loop from the api object

2021-07-27 09:28 UTC, remidej commented on src/fetch.js
> +    if (typeof loop === 'number') {
Please also check if it's a integer (no decimals) and >= 1

2021-07-27 09:28 UTC, remidej commented on src/fetch.js
> +  _start = 0
Can you replace these arguments with an object? This way it will be easier to read when calling that function

2021-07-27 09:28 UTC, remidej commented on src/fetch.js
> +  loop,
We can make the default value 1

2021-07-27 09:28 UTC, remidej commented on src/fetch.js
> +    //ended
Please make this comment more explicit

2021-07-27 09:28 UTC, remidej commented on src/fetch.js
> +  return fetchLoop(reporter, queryLimit, requestOptions, loop, newResults, _start + loop);
Please add a comment to make this recursion easier to read

2021-07-27 09:28 UTC, remidej commented on src/index.js
> +      loop: type.loop,
This shouldn't be needed if we move it to the API object

2021-08-08 13:46 UTC, zsrl commented
When can this feature be released? 
I think I need it.
@philippeauriach @remidej

2021-08-08 19:45 UTC, philippeauriach commented
@remidej Changes made according to suggestions, thanks for your review. The only issue i didn't address is the part y ou ask for an explicit comment about the recursion, if you have an idea that would be nice ?
thanks

2021-09-09 22:42 UTC, FredWahlqvistDrop commented
Hey @remidej, is there anything we can do to so this can be merged?

2022-02-17 09:40 UTC, soupette commented
I am closing the PR as a new version has been released, feel free to reopen it.

2022-02-17 09:44 UTC, laurenskling commented
Since v2 is only compatible for Strapi 4, this fix would still be highly appreciated for us using Strapi 3 (MongoDB say hello 👋)

2022-03-10 20:46 UTC, laurenskling commented
Would it be possible for this to be merged in as `1.1` @soupette ? Really, this plugin cannot be run without this fix. Without this, how would one load any data over a couple of hundred entries? 
Since you are planning to go v2 for Strapi v4. Please merge this in as `1.1` for us poor souls running Strapi v3.

2022-06-18 10:05 UTC, laurenskling commented
I've been running this code for a while now using `patch-package` and it's been working great for me. On cold build.

I just realized that on incremental builds on Gatsby Cloud, the loop isn't running. My assumption here is that Gatsby Cloud incremental builds (which detect a Strapi webhook) run their installed version of the source plugin, not my patched one.

So still I would really really really love to see this feature released as a version `1.1` or something for us (still stuck at) running projects on Strapi 3. I don't see any downsides in doing so.

If this PR needs any work still, I would be super happy to work on it.

2022-06-28 08:24 UTC, soupette commented
@laurenskling have tried to the new version with the Strapi V4? It does support Gatsby incremental build

2022-06-28 11:26 UTC, laurenskling commented
@soupette yes I know the v4 version is updated, but i'm running 10+ codebases on Strapi 3, and for all of them I need to: switch from mongo to sql, change all database fields to snake_case, update all my code, update all my plugins code, update my frontend code to use the new GraphQL output. It's not something I can do overnight, it will take me months, many months, before I'm ready to fully switch to v4. 
I am in the process, but until it's ready (probably need a full year for it), i would really really like it if we can get these little code snippets with big impact into v3. Thanks.

2022-11-30 10:51 UTC, remidej commented
Closing this as it's targeting Strapi v3, which [reaches end of life](https://strapi.io/blog/end-of-the-road-for-strapi-v3) in a month, so we won't maintain the v3 version of this source plugin either

2022-11-30 10:51 UTC, closed without merging