Support undefined singleTypes in strapi config
strapi/gatsby-source-strapi pull request #304
Opened 2022-03-16 17:31 UTC by remidej

Fixes #303

Currently, if the user has no single types, he still has to add `singleTypes: []` to his config. If he doesn't, the app will crash.

This PR changes that behavior by making the singleTypes and collectionTypes optional. It will also make it easier to migrate from the source plugin v1 to v2, since this is how it already worked before.

2022-03-17 08:27 UTC, soupette requested changes

2022-03-17 08:27 UTC, soupette commented on src/gatsby-node.js
> +  if (pluginOptions.singleTypes == null) {
```js
if (!Array.isArray(pluginOptions.singleTypes)) { /.../ }
if (!Array.isArray(pluginOptions.collectionTypes)) { /.../ }
```

2022-03-18 10:41 UTC, markkaylor approved these changes
Looks good to me

2022-03-18 15:55 UTC, soupette approved these changes

2022-03-21 08:30 UTC, merged